api:
  build: rails/.
  volumes:
    - ./rails:/src
  links:
    - redis
    - mysql
  ports:
    - "3000:3000"
  command: ./start.sh
  dns: 8.8.8.8
redis:
  image: dockerfile/redis
node:
  image: dockerfile/nodejs
  links:
    - redis
  command: /bin/bash
mysql:
  image: dockerfile/mysql
